#!/usr/bin/env node
// PreCompact hook (ClaudeOS v8.3)
// 1M context rot 対策として、/compact 実行前に state.json を退避する。
// 加えて evacuation-latest.json へ蒸留した再開情報を書き出す (Memory MCP 退避の補完)。
// 退避失敗時は exitCode 2 を返して /compact をブロックする。
// state.json の更新は atomic write (temp + rename) で並列読み書き競合を回避する。

const fs = require("fs");
const path = require("path");

const PROJECT_ROOT = process.cwd();
const STATE_FILE = path.join(PROJECT_ROOT, "state.json");
const SNAPSHOT_DIR = path.join(
  PROJECT_ROOT,
  ".claude",
  "claudeos",
  "snapshots"
);

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

function writeJsonAtomic(file, data) {
  const tmp = `${file}.tmp.${process.pid}`;
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + "\n", "utf8");
  fs.renameSync(tmp, file);
}

function snapshotState() {
  // copyFileSync を直接 try で囲み、TOCTOU リスクを回避する。
  ensureDir(SNAPSHOT_DIR);
  const dest = path.join(SNAPSHOT_DIR, `state.${timestamp()}.json`);
  try {
    fs.copyFileSync(STATE_FILE, dest);
    return { snapshotPath: dest };
  } catch (err) {
    if (err.code === "ENOENT") {
      return { skipped: true, reason: "state.json not found" };
    }
    throw err;
  }
}

function recordCompactTimestamp() {
  const state = readJson(STATE_FILE);
  if (!state) return;
  state.compact = state.compact || {};
  state.compact.last_pre_compact_at = new Date().toISOString();
  writeJsonAtomic(STATE_FILE, state);
}

function pruneOldSnapshots(keep = 20) {
  if (!fs.existsSync(SNAPSHOT_DIR)) return;
  const files = fs
    .readdirSync(SNAPSHOT_DIR)
    .filter((f) => f.startsWith("state.") && f.endsWith(".json"))
    .map((f) => ({
      name: f,
      mtime: fs.statSync(path.join(SNAPSHOT_DIR, f)).mtimeMs,
    }))
    .sort((a, b) => b.mtime - a.mtime);
  files.slice(keep).forEach((f) =>
    fs.unlinkSync(path.join(SNAPSHOT_DIR, f.name))
  );
}

// Memory MCP 退避の補完: 蒸留した再開情報を evacuation-latest.json へ書き出す。
// Claude 側の memory-mcp-evacuation.md フックがこのファイルを補助資料として参照できる。
// Dreaming (Research Preview) と Orchestration Event Log のフィールドを含む。
function writeEvacuationSummary(state) {
  if (!state) return null;
  const exec = state.execution || {};
  const stable = state.stable || {};
  const dreaming = state.dreaming || {};
  const evacuation = {
    evacuated_at: new Date().toISOString(),
    phase: exec.phase || null,
    last_session_summary: exec.last_session_summary || null,
    last_stop_at: exec.last_stop_at || null,
    stable_achieved: stable.stable_achieved || false,
    consecutive_success: stable.consecutive_success || 0,
    last_verified_at: stable.last_verified_at || null,
    // Dreaming フィールド (Research Preview 準備 — アクセス取得後に populate される)
    dreaming_patterns: dreaming.patterns || [],
    curated_memories: dreaming.curated_memories || [],
    recurring_mistakes: dreaming.recurring_mistakes || [],
    // Orchestration Event Log 最新 10 件 (Managed Agents Orchestration 統合)
    orchestration_events: (exec.orchestration_events || []).slice(-10),
    note: "Generated by pre-compact.js — supplements memory-mcp-evacuation.md hook",
  };
  ensureDir(SNAPSHOT_DIR);
  const dest = path.join(SNAPSHOT_DIR, "evacuation-latest.json");
  writeJsonAtomic(dest, evacuation);
  return dest;
}

try {
  const result = snapshotState();
  const state = readJson(STATE_FILE);
  const evacuationPath = writeEvacuationSummary(state);
  recordCompactTimestamp();
  pruneOldSnapshots(20);

  if (result.skipped) {
    console.log(`[PreCompact] skipped: ${result.reason}`);
  } else {
    console.log(`[PreCompact] state snapshot saved: ${result.snapshotPath}`);
  }
  if (evacuationPath) {
    console.log(`[PreCompact] evacuation summary written: ${evacuationPath}`);
  }
  process.exit(0);
} catch (err) {
  console.error(`[PreCompact] FAILED: ${err.message}`);
  // exitCode 2 = block /compact (Claude Code hook spec)
  process.exit(2);
}
